[build]
  command = "yarn install && yarn build"
  publish = "app/dist"
  base = "app"

[context.production]
  [context.production.environment]
    NPM_FLAGS = "--ignore-scripts"
    YARN_FLAGS = "--immutable"
    NODE_VERSION = "18.20.2"
    YARN_VERSION = "1.22.22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
